import React, { Component } from 'react'

/** 
 * Biography renders a large name-and-title block.
 */
class Biography extends Component {
  render() {
    return (
      <section className="bio shorten staffonly">
        <p>Professor Peter A. Leggat, AM, is Professor and Deputy Dean in the <a href="https://www.jcu.edu.au/college-of-public-health-medical-and-veterinary-sciences" target="_blank">College of Public Health, Medical and Veterinary Sciences</a>, Division of Tropical Health and Medicine, <a href="http://www.jcu.edu.au" target="_blank">James Cook University</a> (JCU), Australia. He has a strong interest in health workforce development in public health and tropical medicine, but also in related areas such as aerospace and travel medicine. He also founded the <a href="http://www.pitt.edu/~super1/collections/collection51.htm" target="_blank">Supercourse Travel Medicine Course</a> with eight lectures. He has consulted with various organisations, including the <a href="http://www.defence.gov.au/" target="_blank">Australian Defence Force</a>, the <a href="https://www.tga.gov.au/" target="_blank">Therapeutic Goods Administration</a> (Australia) and the <a href="http://who.int/en/" target="_blank">World Health Organization</a>.&nbsp;</p>
        <p>Professor Leggat graduated in medical science and medicine from the <a href="http://www.uq.edu.au/" target="_blank">University of Queensland</a>. He undertook postgraduate studies at various universities, including <a href="http://www.mahidol.ac.th/en/" target="_blank">Mahidol University</a>, the <a href="http://www.dundee.ac.uk" target="_blank">University of Dundee</a> and the <a href="http://www.otago.ac.nz" target="_blank">University of Otago</a>, before completing doctorates at the <a href="http://www.unisa.edu.au/" target="_blank">University of South Australia</a> and <a href="https://www.jcu.edu.au/" target="_blank">James Cook University</a> and a higher doctorate at the <a href="http://uq.edu.au/" target="_blank">University of Queensland</a>. He has also specialised in <a href="http://www.racgp.org.au" target="_blank">General Practice</a>, <a href="https://members.racp.edu.au/page/racp-faculties/australasian-faculty-of-public-health-medicine/" target="_blank">Public Health Medicine</a> and <a href="http://www.aerospacemedicine.org.au" target="_blank">Aerospace Medicine</a>. As part of a <a href="http://fulbright.com.au/" target="_blank">Fulbright Scholarship</a>, he completed the Primary Care Faculty Development Fellowship Program at <a href="http://www.msu.edu/" target="_blank">Michigan State University</a>. A current Fulbright Ambassador, his research encompasses a broad range of topics including occupational health issues for health care workers, public health aspects of disasters, and health and safety concerns for travellers. He has published&nbsp; &gt;500 journal papers (<a href="http://scholar.google.com/citations?user=7XgY0qcAAAAJ&amp;hl=en" target="_blank">&gt;4000 citations; <em>h-</em>index=31; i10-index=119</a>), and &gt;90 chapters, as well as &gt;35 books, directories and proceedings. His most recently published textbook is <a href="http://onlinelibrary.wiley.com/book/10.1002/9781118597361" target="_blank"><em>Essential Travel Medicine</em></a> (Wiley Blackwell, Oxford, UK, 2015)<em>. </em>He has presented &gt;350 papers at national and international conferences.&nbsp;</p>
        <p>Professor Leggat holds a number of professional and other Board appointments. These include the <a href="http://www-public.jcu.edu.au/public/groups/everyone/documents/membership/jcuprd1_062778.pdf" target="_blank">JCU Council,</a> <a title="World Safety Organization" href="http://www.worldsafety.org" target="_blank">World Safety Organization</a> (formerly Director-General, 1997-99), <a title="International Society of Travel Medicine" href="http://www.istm.org" target="_blank">International Society of Travel Medicine </a>(Secretary-Treasurer), <a title="The Australasian College of Aerospace Medicine" href="http://www.aerospacemedicine.org.au" target="_blank">The Australasian College of Aerospace Medicine </a>(Dean of Education), <a title="The Australasian College of Tropical Medicine" href="http://www.tropmed.org" target="_blank">The Australasian College of Tropical Medicine</a> (ACTM) (President), and the <a href="http://www.travelmedicine.org.au/" target="_blank">Faculty of Travel Medicine</a>, (Dean), ACTM. He was elected a Fellow of the <a href="http://www.companydirectors.com.au/" target="_blank">Australian Institute of Company Directors</a> in 1991 and has been the recipient of numerous awards and honours (selected Awards and honours from the past 10 years are given under Honours), including admission as a <a href="https://www.gg.gov.au/sites/default/files/files/honours/qb/qb2013/Gazette%20O%20of%20A%281%29.pdf" target="_blank">Member of the Order of Australia</a> in 2013 and an <a href="https://www.legislation.gov.au/Details/C2016G01262" target="_blank">Commander of the Order of St John</a> in 2016.</p>
      </section>
    )
  }
}

export default Biography